schema=1
series=25.12
release=25.12.5-r1
channel=testing
architecture=aarch64_cortex-a53
index_url=https://tifycloud.github.io/NexaWrt/packages/25.12/testing/aarch64_cortex-a53/packages.adb
public_sha256=21e799c1c16b1fae53ad2e5614c5b85beb3841a326116dfb2d80fe136ddb9093
